# Generated by Django 2.2.7 on 2019-11-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(help_text='Activity (e.g. TG1, TG2, TG3, ...)', max_length=3)),
                ('description', models.CharField(help_text='Activity description', max_length=20)),
                ('productive', models.BooleanField(default=False, help_text='Is this Activity considered to be productive')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(help_text='Tag Name', max_length=20)),
                ('tag_hex', models.CharField(help_text='Tag Color in Hex', max_length=6)),
            ],
        ),
    ]
