# Generated by Django 2.2.7 on 2019-12-08 16:40

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(help_text='Activity (e.g. TG1, TG2, TG3, ...)', max_length=3, verbose_name='Activity: Activity Name')),
                ('description', models.CharField(help_text='Activity description', max_length=20, verbose_name='Activity: Description')),
                ('productive', models.BooleanField(default=False, help_text='Is this Activity considered to be productive', verbose_name='Activity: Productive')),
            ],
            options={
                'verbose_name': 'activity',
                'verbose_name_plural': 'activities',
                'ordering': ['activity_name'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('target', models.DurationField(default=datetime.timedelta(seconds=25200))),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(help_text='Tag Name', max_length=20, verbose_name='Tag Name')),
                ('tag_hex', models.CharField(help_text='Tag Color in Hexadecimal', max_length=6, validators=[django.core.validators.RegexValidator(message='No valid Hex Color code', regex='^([0-9a-fA-F]{6})$')], verbose_name='Color:')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('user_img', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('location', models.CharField(max_length=30)),
                ('org_name', models.CharField(max_length=30)),
                ('ccenter', models.CharField(max_length=6)),
                ('start', models.DateField()),
                ('normal_start', models.TimeField(default=datetime.time(8, 45))),
                ('normal_end', models.TimeField(default=datetime.time(17, 0))),
            ],
        ),
    ]
