# Generated by Django 2.2.7 on 2019-11-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(help_text='Tag Name', max_length=20)),
                ('tag_hex', models.CharField(help_text='Tag Color in Hex', max_length=6)),
            ],
        ),
    ]
