# Generated by Django 2.2.7 on 2019-11-29 20:38

from django.db import migrations

def load_initial_activities(apps, schema_editor):
    Activity = apps.get_model('settings', 'Activity')
    tg = Activity(id=1, activity_name='TG1', description='Project Activity', productive=True)
    tg.save()
    tg = Activity(id=2, activity_name='TG2', description='Sales Activity', productive=False)
    tg.save()
    tg = Activity(id=3, activity_name='TG3', description='Unproductive', productive=False)
    tg.save()
    tg = Activity(id=4, activity_name='TG4', description='Unnkown', productive=False)
    tg.save()
    tg = Activity(id=5, activity_name='TG5', description='Training', productive=False)
    tg.save()
    tg = Activity(id=6, activity_name='TG6', description='Unknown', productive=False)
    tg.save()
    tg = Activity(id=7, activity_name='TG7', description='Vacation/Sick', productive=False)
    tg.save()
    tg = Activity(id=8, activity_name='TG8', description='Research & Development', productive=False)
    tg.save()
    tg = Activity(id=9, activity_name='TG9', description='Internal Order', productive=False)
    tg.save()


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_activities)
    ]
