# Generated by Django 2.2.7 on 2019-12-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_auto_20191203_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('ccenter', models.CharField(max_length=6)),
                ('weekly_hours', models.IntegerField()),
            ],
        ),
    ]
