# Generated by Django 2.2.7 on 2019-11-30 17:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_auto_20191129_2148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['activity_name'], 'verbose_name': 'activity', 'verbose_name_plural': 'activities'},
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_hex',
            field=models.CharField(help_text='Tag Color in Hex', max_length=6, validators=[django.core.validators.MinLengthValidator(6, message='Hex Color code must have exactly 6 characters')], verbose_name='Tag: Hex Light'),
        ),
    ]
