# Generated by Django 2.2.7 on 2019-11-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_auto_20191130_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(help_text='Tag Name', max_length=20, unique=True, verbose_name='Tag: Tag Name'),
        ),
    ]
