# Generated by Django 2.2.7 on 2019-12-07 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('target', models.DurationField(default=datetime.timedelta(seconds=25200))),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='org_name',
            field=models.CharField(default='GP SCD DIGI ENG DTC PTS', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='start',
            field=models.DateField(default=datetime.datetime(2019, 12, 1, 0, 0)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='weekly_hours',
            field=models.DurationField(default=datetime.timedelta(days=1, seconds=39600)),
        ),
    ]
