# Generated by Django 2.2.7 on 2019-12-01 18:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_auto_20191130_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_hex',
            field=models.CharField(help_text='Tag Color in Hex', max_length=6, validators=[django.core.validators.MinLengthValidator(6, message='Hex Color code must have exactly 6 characters')], verbose_name='Tag Color Hex Light'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(help_text='Tag Name', max_length=20, verbose_name='Tag Name'),
        ),
    ]
