# Generated by Django 2.2.7 on 2019-12-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_auto_20191207_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(default='Texas', max_length=30),
            preserve_default=False,
        ),
    ]
