# Generated by Django 2.2.7 on 2019-11-29 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(help_text='Customer Name', max_length=50)),
                ('country', models.CharField(help_text='Customer Country', max_length=50)),
                ('city', models.CharField(blank=True, help_text='Customer City', max_length=50, null=True)),
                ('street', models.CharField(blank=True, help_text='Customer Street', max_length=50, null=True)),
                ('postal', models.CharField(blank=True, help_text='Customer Postal', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(help_text='Project Name', max_length=20)),
                ('active', models.BooleanField(default=True, help_text='Is this Project still active?')),
                ('customer_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(help_text='Activity Group Name', max_length=20)),
                ('active', models.BooleanField(default=True, help_text='Is this Activity Group still active?')),
                ('customer_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_act_type', models.CharField(blank=True, help_text='Code to identify hourly rate (e.g. 012 in TG1012)', max_length=3, null=True)),
                ('receiver_ccenter', models.CharField(default=None, max_length=5, null=True)),
                ('wbs_element', models.CharField(default=None, max_length=20, null=True)),
                ('receiver_order', models.IntegerField(null=True)),
                ('description', models.CharField(max_length=20)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.Activity')),
                ('group', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.Group')),
                ('project', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.Project')),
                ('tag', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.Tag')),
            ],
        ),
    ]
