# Generated by Django 2.2.7 on 2019-11-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='act',
            field=models.IntegerField(blank=True, null=True, verbose_name='Activity'),
        ),
        migrations.AddField(
            model_name='element',
            name='act_description',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='element',
            name='act_type',
            field=models.CharField(blank=True, max_length=6, verbose_name='Activity Type'),
        ),
        migrations.AlterField(
            model_name='element',
            name='element',
            field=models.CharField(max_length=24),
        ),
    ]
