# Generated by Django 2.2.7 on 2019-12-03 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='customer_id',
            field=models.ForeignKey(blank=True, default=None, help_text='Customer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='tracker.Customer'),
        ),
    ]
