# Generated by Django 2.2.7 on 2019-12-02 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='row',
            field=models.IntegerField(choices=[(1, 'Row 1'), (2, 'Row 2'), (2, 'Row 3')], default=1),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, help_text='Customer City', max_length=50, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.CharField(help_text='Customer Country', max_length=50, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_name',
            field=models.CharField(help_text='Customer Name', max_length=50, verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='postal',
            field=models.CharField(blank=True, help_text='Customer Postal Code', max_length=20, verbose_name='Postal'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='street',
            field=models.CharField(blank=True, help_text='Customer Street', max_length=50, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='element',
            name='activity',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elements', to='settings.Activity'),
        ),
        migrations.AlterField(
            model_name='element',
            name='code_act_type',
            field=models.CharField(blank=True, help_text='Code to identify hourly rate (e.g. 012 in TG1012)', max_length=3, verbose_name='Activity Type Code'),
        ),
        migrations.AlterField(
            model_name='element',
            name='description',
            field=models.CharField(max_length=20, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='element',
            name='receiver_ccenter',
            field=models.CharField(blank=True, default=None, max_length=5, verbose_name='Receiver Cost Center'),
        ),
        migrations.AlterField(
            model_name='element',
            name='receiver_order',
            field=models.IntegerField(null=True, verbose_name='Receiver Order'),
        ),
        migrations.AlterField(
            model_name='element',
            name='wbs_element',
            field=models.CharField(blank=True, default=None, max_length=20, verbose_name='WBS Element Name'),
        ),
        migrations.AlterField(
            model_name='group',
            name='active',
            field=models.BooleanField(default=True, help_text='Is this Activity Group still active?', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(help_text='Activity Group Name', max_length=20, verbose_name='Group Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='active',
            field=models.BooleanField(default=True, help_text='Is this Project still active?', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(help_text='Project Name', max_length=20, verbose_name='Project Name'),
        ),
    ]
