# Generated by Django 2.2.7 on 2019-11-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20191120_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='customer_city',
            field=models.CharField(blank=True, help_text='Customer City', max_length=30, null=True),
        ),
    ]
