# Generated by Django 2.2.7 on 2019-12-03 17:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20191202_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='project',
        ),
        migrations.AddField(
            model_name='group',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='tag',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elements', to='settings.Tag'),
        ),
        migrations.AlterField(
            model_name='group',
            name='active',
            field=models.BooleanField(default=True, help_text='Is this Element Group still active?', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='group',
            name='customer_id',
            field=models.ForeignKey(blank=True, default=None, help_text='Customer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='tracker.Customer', verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(help_text='Element Group Name', max_length=20, verbose_name='Group Name'),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
