# Generated by Django 2.2.7 on 2019-11-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_project_customer_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='active',
            field=models.BooleanField(default=True, help_text='WBS is still active'),
        ),
    ]
