# Generated by Django 2.2.7 on 2019-12-03 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20191203_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
