# Generated by Django 2.2.7 on 2019-11-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_element_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='rest',
            field=models.IntegerField(default=0, help_text='Resting Period in minutes', verbose_name='Resting Period'),
        ),
    ]
