# Generated by Django 2.2.7 on 2019-11-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_entry_rest'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='booked',
            field=models.BooleanField(default=False, help_text='Entry is booked in SAP', verbose_name='Booked'),
        ),
    ]
