# Generated by Django 2.2.7 on 2019-11-26 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_entry_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='end',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='start',
        ),
        migrations.AlterField(
            model_name='element',
            name='act',
            field=models.IntegerField(help_text='Activity for this WBS/PSP', verbose_name='Activity'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='duration',
            field=models.IntegerField(help_text='Duration in minutes', verbose_name='Duration'),
        ),
    ]
