# Generated by Django 2.2.7 on 2019-12-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20191203_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
            ],
        ),
    ]
