# Generated by Django 2.2.7 on 2019-12-03 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_auto_20191203_1911'),
        ('tracker', '0007_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField(verbose_name='Starting Time')),
                ('end', models.TimeField(verbose_name='Ending Time')),
                ('timeout', models.DurationField(verbose_name='Duration of break time')),
                ('duration', models.DurationField(verbose_name='Duration of time attributed to Element')),
                ('description', models.CharField(max_length=20, verbose_name='Description of Entry (default is description of parent Element)')),
                ('date', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='tracker.Day')),
                ('element', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='tracker.Element')),
                ('tag', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='settings.Tag')),
            ],
            options={
                'verbose_name': 'entry',
                'verbose_name_plural': 'entries',
            },
        ),
        migrations.AddField(
            model_name='day',
            name='element',
            field=models.ManyToManyField(related_name='days', through='tracker.Entry', to='tracker.Element'),
        ),
    ]
