# Generated by Django 2.2.7 on 2019-12-04 18:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_auto_20191203_2234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-date'], 'verbose_name': 'entry', 'verbose_name_plural': 'entries'},
        ),
        migrations.AddField(
            model_name='day',
            name='end',
            field=models.TimeField(default=datetime.datetime(2019, 12, 4, 18, 12, 7, 800298, tzinfo=utc), verbose_name='Working Day End Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='day',
            name='start',
            field=models.TimeField(default=datetime.datetime(2019, 12, 4, 18, 12, 26, 316078, tzinfo=utc), verbose_name='Working Day Start Time'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='row',
            field=models.IntegerField(choices=[(1, 'Row 1'), (2, 'Row 2'), (3, 'Row 3')], default=1),
        ),
    ]
