# Generated by Django 2.2.7 on 2019-12-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_auto_20191204_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='is_vacation',
            field=models.BooleanField(default=False, verbose_name='Vacation'),
        ),
    ]
