# Generated by Django 2.2.7 on 2019-12-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_day_is_vacation'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='is_public_holiday',
            field=models.BooleanField(default=False, verbose_name='Public Holiday'),
        ),
    ]
