# Generated by Django 2.2.7 on 2019-12-06 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_auto_20191206_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='timeout',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Total Break on this day'),
        ),
    ]
