# Generated by Django 2.2.7 on 2019-12-06 19:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_day_timeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='target',
            field=models.DurationField(default=datetime.timedelta(seconds=25200), verbose_name='Contractual Hours'),
        ),
    ]
