# Generated by Django 2.2.7 on 2019-12-07 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_day_target'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='target',
        ),
        migrations.AddField(
            model_name='day',
            name='withdrawal',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='One-time withdrawal'),
        ),
    ]
