# Generated by Django 2.2.7 on 2019-12-07 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_auto_20191207_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='end',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='start',
        ),
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='tracker.Day'),
        ),
    ]
