# Generated by Django 2.2.7 on 2019-12-07 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_auto_20191207_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='timeout',
        ),
    ]
