# Generated by Django 2.2.7 on 2019-12-08 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_remove_entry_timeout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='tracker.Group'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='description',
            field=models.CharField(blank=True, help_text='Will inherit description from Element if left empty', max_length=20, verbose_name='Description of Entry'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='duration',
            field=models.DurationField(help_text='Duration in HH:mm:ss Format', verbose_name='Duration of time attributed to Element'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='tracker.Element'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='tag',
            field=models.ForeignKey(blank=True, default=None, help_text='Will inherit Tag from Element if left empty and Element has a Tag', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='settings.Tag'),
        ),
    ]
